name: apartment_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.1
  flutter_svg: ^1.0.3
  otp_text_field: ^1.1.3
  flutter_gen: ^4.1.6

dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^1.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBlack.otf
        - asset: assets/fonts/AvenirLTProBook.otf
        - asset: assets/fonts/AvenirLTProHeavy.otf
        - asset: assets/fonts/AvenirLTProLight.otf
        - asset: assets/fonts/AvenirLTProMedium.otf
        - asset: assets/fonts/AvenirLTProRoman.otf


  #   - family: Trajan Pro
